FROM ros:jazzy-ros-base-noble

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends \
      python3-colcon-common-extensions \
      python3-serial \
      python3-pytest \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY src /workspace/src

RUN source /opt/ros/jazzy/setup.bash \
    && apt-get update \
    && rosdep update \
    && rosdep install \
         --from-paths src \
         --ignore-src \
         --rosdistro jazzy \
         -r -y \
    && colcon build --event-handlers console_direct+ \
    && rm -rf /var/lib/apt/lists/*
