"""Crosswalk data loading and local geometry from the standalone v6 prototype."""

import json
import math
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Tuple


Crosswalk = Dict[str, Any]


def number(value: Any) -> Optional[float]:
    """Parse a finite number without accepting bool or non-finite values."""

    if value is None or isinstance(value, bool):
        return None
    try:
        text = str(value).strip().replace(',', '')
        parsed = float(text)
    except (TypeError, ValueError):
        return None
    return parsed if math.isfinite(parsed) else None


def _first_value(record: Mapping[str, Any], names: Iterable[str]) -> Any:
    for name in names:
        value = record.get(name)
        if value not in (None, ''):
            return value
    return None


def _rows(document: Any) -> List[Mapping[str, Any]]:
    if isinstance(document, list):
        return [row for row in document if isinstance(row, dict)]
    if isinstance(document, dict):
        for key in ('data', 'items', 'row', 'list'):
            candidate = document.get(key)
            if isinstance(candidate, list):
                return [row for row in candidate if isinstance(row, dict)]
    raise ValueError('crosswalk JSON does not contain a record list')


def load_crosswalks(path: str) -> List[Crosswalk]:
    """Load normalized crosswalk records generated by the v2 converter."""

    source = Path(path).expanduser()
    with source.open(encoding='utf-8-sig') as stream:
        document = json.load(stream)

    result: List[Crosswalk] = []
    for index, row in enumerate(_rows(document)):
        latitude = number(_first_value(row, ('latitude', 'lat', 'y')))
        longitude = number(
            _first_value(row, ('longitude', 'lon', 'lng', 'x'))
        )
        length = number(
            _first_value(row, ('length_m', 'crswlkLt', 'et', 'length'))
        )
        width = number(
            _first_value(row, ('width_m', 'crswlkBt', 'bt', 'width'))
        )
        axis_bearing = number(
            _first_value(
                row,
                ('axis_bearing_deg', 'axis_bearing', 'bearing_deg'),
            )
        )
        intersection_id = _first_value(
            row,
            ('intersection_id', 'itst_id', 'itstId'),
        )

        if (
            latitude is None
            or longitude is None
            or not -90.0 <= latitude <= 90.0
            or not -180.0 <= longitude <= 180.0
            or length is None
            or length <= 0.0
            or axis_bearing is None
        ):
            continue

        result.append(
            {
                'index': index,
                'latitude': latitude,
                'longitude': longitude,
                'length_m': length,
                'width_m': max(width or 0.0, 0.0),
                'axis_bearing_deg': axis_bearing % 180.0,
                'intersection_id': (
                    '' if intersection_id in (None, '')
                    else str(intersection_id).strip()
                ),
            }
        )

    if not result:
        raise ValueError('crosswalk JSON contains no valid records')
    return result


def haversine_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    radius = 6_371_000.0
    first = math.radians(lat1)
    second = math.radians(lat2)
    delta_latitude = math.radians(lat2 - lat1)
    delta_longitude = math.radians(lon2 - lon1)
    value = (
        math.sin(delta_latitude / 2.0) ** 2
        + math.cos(first)
        * math.cos(second)
        * math.sin(delta_longitude / 2.0) ** 2
    )
    return 2.0 * radius * math.asin(math.sqrt(value))


def bearing_deg(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    first = math.radians(lat1)
    second = math.radians(lat2)
    delta_longitude = math.radians(lon2 - lon1)
    y = math.sin(delta_longitude) * math.cos(second)
    x = (
        math.cos(first) * math.sin(second)
        - math.sin(first) * math.cos(second) * math.cos(delta_longitude)
    )
    return (math.degrees(math.atan2(y, x)) + 360.0) % 360.0


def bearing_to_direction(angle: float) -> str:
    directions = ('nt', 'ne', 'et', 'se', 'st', 'sw', 'wt', 'nw')
    return directions[int((angle + 22.5) // 45.0) % 8]


def angular_difference_deg(first: float, second: float) -> float:
    return abs((first - second + 180.0) % 360.0 - 180.0)


def undirected_axis_difference_deg(first: float, second: float) -> float:
    difference = angular_difference_deg(first, second)
    return min(difference, abs(180.0 - difference))


def local_offset_m(
    origin_latitude: float,
    origin_longitude: float,
    target_latitude: float,
    target_longitude: float,
) -> Tuple[float, float]:
    north = (target_latitude - origin_latitude) * 111_320.0
    east = (
        (target_longitude - origin_longitude)
        * 111_320.0
        * math.cos(
            math.radians((origin_latitude + target_latitude) / 2.0)
        )
    )
    return east, north


def crosswalk_edge_distance_m(
    item: Mapping[str, Any],
    user_latitude: float,
    user_longitude: float,
) -> float:
    east, north = local_offset_m(
        float(item['latitude']),
        float(item['longitude']),
        user_latitude,
        user_longitude,
    )
    bearing = math.radians(float(item['axis_bearing_deg']))
    axis_east, axis_north = math.sin(bearing), math.cos(bearing)
    side_east, side_north = (
        math.sin(bearing + math.pi / 2.0),
        math.cos(bearing + math.pi / 2.0),
    )
    along = east * axis_east + north * axis_north
    across = east * side_east + north * side_north
    outside_along = max(abs(along) - float(item['length_m']) / 2.0, 0.0)
    outside_across = max(
        abs(across) - float(item.get('width_m') or 0.0) / 2.0,
        0.0,
    )
    return math.hypot(outside_along, outside_across)


def nearest_crosswalk(
    crosswalks: Iterable[Mapping[str, Any]],
    latitude: float,
    longitude: float,
) -> Optional[Crosswalk]:
    """Return the nearest polygon plus the safest crossing orientation."""

    best: Optional[Mapping[str, Any]] = None
    best_edge_distance = math.inf
    for item in crosswalks:
        edge_distance = crosswalk_edge_distance_m(item, latitude, longitude)
        if edge_distance < best_edge_distance:
            best = item
            best_edge_distance = edge_distance
    if best is None:
        return None

    output = dict(best)
    output['edge_distance_m'] = best_edge_distance
    output['center_distance_m'] = haversine_m(
        latitude,
        longitude,
        float(best['latitude']),
        float(best['longitude']),
    )
    target_bearing = bearing_deg(
        latitude,
        longitude,
        float(best['latitude']),
        float(best['longitude']),
    )
    axis_a = float(best['axis_bearing_deg']) % 360.0
    axis_b = (axis_a + 180.0) % 360.0
    crossing_bearing = (
        axis_a
        if angular_difference_deg(target_bearing, axis_a)
        <= angular_difference_deg(target_bearing, axis_b)
        else axis_b
    )
    signal_bearing = (crossing_bearing + 90.0) % 360.0
    output.update(
        {
            'target_bearing_deg': target_bearing,
            'crossing_bearing_deg': crossing_bearing,
            'crossing_direction': bearing_to_direction(crossing_bearing),
            'signal_bearing_deg': signal_bearing,
            'signal_direction': bearing_to_direction(signal_bearing),
            'axis_alignment_error_deg': undirected_axis_difference_deg(
                target_bearing,
                axis_a,
            ),
        }
    )
    return output


def crosswalk_axis_position(
    item: Mapping[str, Any],
    latitude: float,
    longitude: float,
    crossing_bearing_deg: float,
) -> Dict[str, float]:
    east, north = local_offset_m(
        float(item['latitude']),
        float(item['longitude']),
        latitude,
        longitude,
    )
    bearing = math.radians(crossing_bearing_deg)
    axis_east, axis_north = math.sin(bearing), math.cos(bearing)
    side_east, side_north = (
        math.sin(bearing + math.pi / 2.0),
        math.cos(bearing + math.pi / 2.0),
    )
    along = east * axis_east + north * axis_north
    across = east * side_east + north * side_north
    progress = along + float(item['length_m']) / 2.0
    return {
        'along_m': along,
        'across_m': across,
        'progress_m': progress,
        'remaining_m': max(float(item['length_m']) - progress, 0.0),
        'lateral_error_m': max(
            abs(across) - float(item.get('width_m') or 0.0) / 2.0,
            0.0,
        ),
    }


def evaluate_locked_crosswalk(
    item: Mapping[str, Any],
    latitude: float,
    longitude: float,
) -> Crosswalk:
    output = dict(item)
    output['center_distance_m'] = haversine_m(
        latitude,
        longitude,
        float(item['latitude']),
        float(item['longitude']),
    )
    output['edge_distance_m'] = crosswalk_edge_distance_m(
        item,
        latitude,
        longitude,
    )
    output.update(
        crosswalk_axis_position(
            item,
            latitude,
            longitude,
            float(item['crossing_bearing_deg']),
        )
    )
    return output


__all__ = [
    'angular_difference_deg',
    'bearing_to_direction',
    'crosswalk_axis_position',
    'crosswalk_edge_distance_m',
    'evaluate_locked_crosswalk',
    'haversine_m',
    'load_crosswalks',
    'nearest_crosswalk',
    'number',
]
